Dev 11 minimal application code
KatherLab/MediSwarm pull request #15
Opened 2024-10-16 08:56 UTC by oleschwen

This application code serves two purposes

- testing a training that runs quickly without depending on any data to be present
- example for writing own application code using pytorch.

2024-10-24 10:34 UTC, Ultimate-Storm requested changes
Thanks for your work, can be merged after adding a ReadME

2024-10-24 10:34 UTC, Ultimate-Storm commented on application/jobs/minimal_training_test/app/config/config_fed_client.conf
> +{
Shall we change the name of the script to [config_swarm_client.conf] ?

2024-10-24 10:34 UTC, Ultimate-Storm commented on application/jobs/minimal_training_test/app/custom/env_config.py
> +def load_environment_variables():
We can delete this block

2024-10-24 10:34 UTC, Ultimate-Storm commented on application/jobs/minimal_training_test/meta.conf
> +name = "minimal_training"
Do we need a more illustrative name like minimal_training_3dcnn, or we can specify it within the ReadME

2024-10-24 11:27 UTC, oleschwen commented on application/jobs/minimal_training_test/app/config/config_fed_client.conf
> +{
Yes, I'll change it.
As I copied this from a different job folder, we should also adapt it there.

2024-10-24 11:27 UTC, oleschwen commented on application/jobs/minimal_training_test/app/custom/env_config.py
> +def load_environment_variables():
Yes, I'll change it.

2024-10-24 11:28 UTC, oleschwen commented on application/jobs/minimal_training_test/meta.conf
> +name = "minimal_training"
It's 2D :-) but yes, the name could be more specific. minimal_training_pytorch_cnn?

2024-10-24 13:25 UTC, oleschwen commented on application/jobs/minimal_training_test/app/config/config_fed_client.conf
> +{
Unable. The expected file names are hard-coded in NVFlare.

2024-10-24 13:34 UTC, oleschwen commented
I've created a README.md in the application code folder.
This is getting a bit redundant with other application code, I'll create a follow-up issue to refactor documentation, also taking into account #14.

2024-10-25 08:49 UTC, oleschwen commented on application/jobs/minimal_training_test/app/custom/env_config.py
> +def load_environment_variables():
Actually, it is needed. But there is no reason to have a separate file `env_config.py`; the code can go directly in `minimal_training.py`.

2025-01-31 12:48 UTC, Ultimate-Storm approved these changes
Looks good to me

2025-01-31 13:23 UTC, merged